name: PyTest

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.8", "3.9", "3.10"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Cet up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('**/*requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy wheel pytest
        python -m pip install git+https://github.com/Siwick-Research-Group/uedinst.git
        python -m pip install -r requirements.txt
        python setup.py install
    - name: Unit tests
      run: | 
        cd ~
        python -m pytest --pyargs DectrisTools
